export default {
	ADD_NEW_ITEM: "ADD_NEW_ITEM",

	PASTE_ITEM: "PASTE_ITEM",

	UPDATE_POSITION: "UPDATE_POSITION",

  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  
  UNDO_ACTION: "UNDO_ACTION",

  REDO_ACTION: "REDO_TYPE",
  
	DEFAULT_ADD_HISTORY: "DEFAULT_ADD_HISTORY"
}
